== Start Koin with Android

The `koin-android` project is dedicated to provide Koin powers to Android world.

=== startKoin() from your Application

From your `Application` class you can use the `startKoin()` function:

[source,kotlin]
----
class MainApplication : Application() {

    override fun onCreate() {
        super.onCreate()

        startKoin(this, myAppModules)
    }
}
----


=== Starting Koin with Android context from elsewhere?

If you need to start Koin from another Android class, you can use the `startKoin()` function and provide your Android `Context`
instance with just like:

[source,kotlin]
----
// Start Koin and init Application instance definition
startKoin(androidContext, myAppModules)
----

Also, there is a `with` operator that can help you bind the `Context` instance in the case of non Android class (Junit for example). It can help like follow:

.Example of mocking Androic context in a JUnit
[source,kotlin]
----
// Start Koin and init Context instance definition
startKoin(myAppModules) with (mock(Context::class.java))
----

=== Koin Logging

With the `startKoin()` function, we have a parameter `logger` which has a default value: `AndroidLogger()`.
This logger is an Android implementation of the Koin logger.

Up to you to change this logger if it doesn't suits to your needs.

.Shut off Koin Logger
[source,kotlin]
----
class MainApplication : Application() {

    override fun onCreate() {
        super.onCreate()

        startKoin(this, myAppModules, logger = EmptyLogger())
    }
}
----

=== Properties

You can use Koin properties in the `assets/koin.properties` file, to store keys/values. You can also use extraProperties at start:

.Use Koin extra properties
[source,kotlin]
----
// Shut off Koin Logger
class MainApplication : Application() {

    override fun onCreate() {
        super.onCreate()

        startKoin(this, myAppModules, extraProperties = mapOf( ... ))
    }
}
----

