== Architecture Components with Koin: ViewModel

The `koin-android-viewmodel` project is dedicated to bring Android Architecture VieModel features.

=== Gradle setup

Choose the `koin-android-viewmodel` dependency to add to your Gradle project (android or androix version):

[source,gradle,subs="attributes"]
----
// Add Jcenter to your repositories if needed
repositories {
    jcenter()
}
dependencies {
    // ViewModel for Android
    compile 'org.koin:koin-android-viewmodel:{revnumber}'
    // or ViewModel for AndroidX
    compile 'org.koin:koin-androidx-viewmodel:{revnumber}'
}
----

=== DSL enhancements

Below are some DSL related features.

=== Easily build your definition

It's possible to avoid inject your definition using `get()` in your definitions to simplify your writing. The `build()` function
will help you build your component by taking it's first constructor and injecting dependencies.

Below you can compare the two ways of injecting inside definitions:

[source,kotlin]
----
    class ComponentA
    class ComponentB(val a: ComponentA)
    class ComponentC(val a: ComponentA, val b: ComponentB)

    // directly inject definitions with get()
    val noReflect = module {
           single { ComponentA() }
           single { ComponentB(get()) }
           single { ComponentC(get(),get()) }
       }

    // don't use get
    val buildwithReflect = module {
           single { ComponentA() }
           single { build<ComponentB>() }
           single { build<ComponentC>() }
       }
----

[IMPORTANT]
====
Keep in mind that `build()` function is not just magic, it has also a very small cost (the time to take your constructor and inject each argument). If you care about performances,
don't hesitate to switch your definition writing between get or build to compare the their performances for you.
====








