name: Set up environment for Android build
description: Set up environment for Android build

runs:
  using: composite
  steps:
    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v3

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
