== Koin DSL

Koin provides a DSL to help your describe your components with definitions and start the Koin container
with those definitions and to instantiate them when needed.

=== Why a DSL?

Thanks to the power of Kotlin language, Koin provides a DSL to help your describe your app instead of annotate it. Those annotations need introspection analyze,
proxying/code generation. Whereas with Kotlin DSL, we can use smart functional API to achieve the same goal: make dependency injection.

=== The Koin DSL

Below are the Koin DSL keywords:

* `module` - create a Koin Module
* `factory` - provide a factory bean definition
* `single` - provide a singleton bean definition (also aliased as `bean`)
* `bind` - add type to bind for given bean definition
* `get` - resolve a component dependency

=== Writing a module

A Koin module is the space to declare all your components. Use the `module` function to declare a Koin module:

[source,kotlin]
----
val myModule = module {
   // your dependencies here
}
----

In this module, you can declare components with `single` or `factory` functions, or declare inner modules with `module` function.

=== Defining a singleton

Declaring a singleton component means that Koin container will keep a unique instance of your declared component. Use the `single` function in a module to declare a singleton:

[source,kotlin]
----
//Given a simple class `MyService`
class MyService()

val myModule = module {

    // declare single instance for MyService class
    single { MyService() }
}
----

[IMPORTANT]
====
`single` & `factory` keywords help you declare your components through a lambda expression. this lambda describe
the way that you build your component. Usually we instantiate components via their constructors, but you can also use any expression.

`factory or single { Class constructor / expression }`

The result type of your lambda is the main type of your component
====


=== Defining a factory

A factory component declaration is a definition that will gives you a new instance each time you ask for this definition. Use the `factory` function
with a lambda expression to build a component, like `single` definition above.

[source,kotlin]
----
//Given a simple class `Controller`
class Controller()

val myModule = module {

    // declare factory instance for Controller class
    factory { Controller() }
}
----

[NOTE]
====
Koin containter doesn't retain factory instances as it will give a new instance each time the definition is asked. Then, there is no need to keep in the Koin container.
====

=== Resolving & injecting dependencies

Now that we can declare components definitions, we want to link instances with dependency injection. To resolve an instance in the Koin module, just use the `get()`
function to the requested needed component instance.

[IMPORTANT]
====
To make dependency injection with Koin container, we have to write it in *constructor injection* style: resolve depdendencies in class constructors. This way, your instance will be created with injected intances from Koin.
====

Let's take an example with several classes:

[source,kotlin]
----
// Given Service & Controller classes
// Presenter <- Service
class Service()
class Controller(val view : View)

val myModule = module {

    // declare Service as single intance
    single { Service() }
    // declare Controller as single instance, resolving View instance with get()
    single { Controller(get()) }
}
----

=== Binding an interface

A `single` or a `factory` definition use the type from the their given lambda definition: i.e  `single { type T }`
The matched type of the definition is the only matched type from this expression.

Let's take an example with a class and interface:

[source,kotlin]
----
// Service interface
interface Service{

    fun doSomething()
}

// Service Implementation
class ServiceImp() : Service{

    fun doSomething() { ... }
}
----

In a Koin module we can use the `as` cast Kotlin operator as follow:

[source,kotlin]
----
val myModule = module {

    // Will match type ServiceImp only
    single { ServiceImp() }

    // Will match type Service only
    single { ServiceImp() as Service }

}
----

=== Binding an additional type

In some cases, we want to match several types from one definition.

Let's take an example with a class and interface:

[source,kotlin]
----
// Service interface
interface Service{

    fun doSomething()
}

// Service Implementation
class ServiceImp() : Service{

    fun doSomething() { ... }
}
----

To make a definition that can match additional types, we use the `bind` operator with a class:

[source,kotlin]
----
val myModule = module {

    // Will match types ServiceImp & Service
    single { ServiceImp() } bind Service::class
}
----


=== Conflicting definitions

