== Scope features for Android

The `koin-android-scope` project is dedicated to bring Android scope features.

=== Gradle setup

Choose the `koin-android-scope` dependency to add to your Gradle project (android or androix version):

[source,gradle,subs="attributes"]
----
// Add Jcenter to your repositories if needed
repositories {
    jcenter()
}
dependencies {
    // Scope for Android
    implementation 'org.koin:koin-android-scope:{revnumber}'
    // or Scope for AndroidX
    implementation 'org.koin:koin-androidx-scope:{revnumber}'
}
----

=== Taming the Android lifecycle

Android components are mainly managed by their lifecycle: we can't directly instantiate an Activity nor a Fragment. The system
make all creation and management for us, and make callbacks on methods: onCreate, onStart...

That's why we can't describe our Activity/Fragment/Service in a Koin module. We need then to inject dependencies into properties and also
respect the lifecycle: Components related to the UI parts must be released on soon as we don't need them anymore.

Then we have:

* long live components (Services, Data Repository ...) - used by several screens, never dropped
* medium live components (user sessions ...) - used by several screens, must be dropped after an amount of time
* short live components (views) - used by only one screen & must be dropped at the end of the screen


Long live components can be easily described as `single` definitions. For medium and short live components we can have several approaches.

In the case of MVP architecture style, the `Presenter` is a short live component to help/support the UI. The presenter must be created each time the screen is showing,
and dropped once the screen is gone.

.A new Presenter is created each time
[source,kotlin]
----
class DetailActivity : AppCompatActivity() {

    // injected Presenter
    override val presenter : Presenter by inject()
----

We can describe it in a module:


* as `factory` - to produce a new instance each time the `by inject()` or `get()` is called

[source,kotlin]
----
val androidModule = module {

    // Facvtory instance of Presenter
    factory { Presenter() }
}
----

* as `single` & `module` - to produce an instance when called and manually drop it when needed

[source,kotlin]
----
val androidModule = module {

    // a dedicated module for Presenter
    module("org.samples.detail"){
        single { Presenter() }
    }
}

// Call release() to release Presenter instance when needed
release("org.samples.detail")
----


[IMPORTANT]
====
Most of Android memory leaks comes from referencing a UI/Android component from a non Android component. Th system keeps a reference
on it and can't totally drop it via garbage collection.
====


=== Binding to lifecycle with scopedWith

Koin gives the `scopedWith` function to bind the actual Android component to listen its lifecycle and release instances of a module.

[source,kotlin]
----
class DetailActivity : AppCompatActivity() {

    // Lazy injected Presenter instance
    override val presenter : Presenter by inject()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // on ON_DESTROY release org.samples.detail module instances
        scopedWith("org.samples.detail")
    }
----

[NOTE]
====
When using the `scopedWith` function, you can specify the end signal on which you want to react: ON_DESTROY | ON_STOP
====

A little function to help you write your scoped module, you can use the `moduleName` property on a class to help declare your module:

[source,kotlin]
----
val androidModule = module {

    // DetailActivity module for Presenter
    module(DetailActivity::class.moduleName){
        single { Presenter() }
    }
}
----

Then you can use the `moduleName` property to easily scope a component:

[source,kotlin]
----
class DetailActivity : AppCompatActivity() {

    // Lazy injected Presenter instance
    override val presenter : Presenter by inject()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // on ON_DESTROY release DetailActivity module instances
        scopedWith(this::class.moduleName)
    }
----


