== Koin DSL

Koin provides a DSL to help your describe your components with definitions and start the Koin container
with those definitions and to instantiate them when needed.

=== Why a DSL?

Thanks to the power of Kotlin language, Koin provides a DSL to help your describe your app instead of annotate it. Those annotations need introspection analyze,
proxying/code generation. Whereas with Kotlin DSL, we can use smart functional API to achieve the same goal: make dependency injection.

=== The Koin DSL

Below are the Koin DSL keywords:

* `module` - create a Koin Module
* `factory` - provide a factory bean definition
* `single` - provide a singleton bean definition (also aliased as `bean`)
* `bind` - add type to bind for given bean definition
* `get` - resolve a component dependency

=== Writing a module

A Koin module is the *space to declare all your components*. Use the `module` function to declare a Koin module:

[source,kotlin]
----
val myModule = module {
   // your dependencies here
}
----

In this module, you can declare components with `single` or `factory` functions, or declare inner modules with `module` function.

=== Defining a singleton

Declaring a singleton component means that Koin container will keep a *unique instance* of your declared component. Use the `single` function in a module to declare a singleton:

[source,kotlin]
----
class MyService()

val myModule = module {

    // declare single instance for MyService class
    single { MyService() }
}
----

[IMPORTANT]
====
`single` & `factory` keywords help you declare your components through a lambda expression. this lambda describe
the way that you build your component. Usually we instantiate components via their constructors, but you can also use any expression.

`factory or single { Class constructor / expression }`

The result type of your lambda is the main type of your component
====


=== Defining a factory

A factory component declaration is a definition that will gives you a *new instance each time* you ask for this definition. Use the `factory` function
with a lambda expression to build a component, like `single` definition above.

[source,kotlin]
----
class Controller()

val myModule = module {

    // declare factory instance for Controller class
    factory { Controller() }
}
----

[NOTE]
====
Koin containter doesn't retain factory instances as it will give a new instance each time the definition is asked. Then, there is no need to keep in the Koin container.
====

=== Resolving & injecting dependencies

Now that we can declare components definitions, we want to link instances with dependency injection. To *resolve an instance* in a Koin module, just use the `get()`
function to the requested needed component instance.

[IMPORTANT]
====
To make dependency injection with Koin container, we have to write it in *constructor injection* style: resolve depdendencies in class constructors. This way, your instance will be created with injected intances from Koin.
====

Let's take an example with several classes:

[source,kotlin]
----
// Presenter <- Service
class Service()
class Controller(val view : View)

val myModule = module {

    // declare Service as single intance
    single { Service() }
    // declare Controller as single instance, resolving View instance with get()
    single { Controller(get()) }
}
----

=== Binding an interface

A `single` or a `factory` definition use the type from the their given lambda definition: i.e  `single { type T }`
The matched type of the definition is the only matched type from this expression.

Let's take an example with a class and interface:

[source,kotlin]
----
// Service interface
interface Service{

    fun doSomething()
}

// Service Implementation
class ServiceImp() : Service{

    fun doSomething() { ... }
}
----

In a Koin module we can use the `as` cast Kotlin operator as follow:

[source,kotlin]
----
val myModule = module {

    // Will match type ServiceImp only
    single { ServiceImp() }

    // Will match type Service only
    single { ServiceImp() as Service }

}
----

=== Binding additional type

In some cases, we want to match several types from one definition.

Let's take an example with a class and interface:

[source,kotlin]
----
// Service interface
interface Service{

    fun doSomething()
}

// Service Implementation
class ServiceImp() : Service{

    fun doSomething() { ... }
}
----

To make a definition that can match additional types, we use the `bind` operator with a class:

[source,kotlin]
----
val myModule = module {

    // Will match types ServiceImp & Service
    single { ServiceImp() } bind Service::class
}
----

=== Overriding a definition

TBD

=== Naming a definition

A definition has by default an empty name. But you can declare a name to your definition, to help you distinguish two definitions about the same type:

Just request your definition with its name:

[source,kotlin]
----
val myModule = module {
    single("default") { ServiceImpl() as Service}
    single("test") { ServiceImpl() as Service }
}

val service : Service by inject(name = "default")
----

`get()` and `by inject()` functions let you specify a definition name if needed.


=== Injection parameters

In any `single` or `factory` definition, you can use injection parameters: parameters that will be injected and used by your definition:

[source,kotlin]
----
class Presenter(val view : View)

val myModule = module {
    single{ view : View -> Presenter(view) }
}
----

In contrary to resolved dependencies (resolved with with `get()`), injection parameters are *parameters passed through the resolution API*.
This means that those parameters are values passed with `get()` and `by inject()`, with the `parametersOf` function:


[source,kotlin]
----
val presenter : Presenter by inject { parametersOf(view) }
----

Further reading in the <<injection-parameters.adoc#_injection_parameters,using injection parameters>> section.

=== Conflicting definitions

Conflicting definitions occurs when you have:

* several definitions that are matching the same type
* defined a circular dependency

In the first case, you can name your definition to distinguish them. You can also use modules to alter resolution visibility. In last case, you can also speify a module path when you request a dependency from a KoinComponent.

[source,kotlin]
----
val myModule = module("org.sample") {


    module("org.demo"){
        single{ ServiceImpl() as Service}
    }

    module("org.sample"){
        single{ ServiceImpl() as Service}
    }
}

// Request dependency from /org/sample namespace
val service : Service by inject(module = "org.sample")
----

For a circular dependency problem, you are in the situation where `A<-B` & `B<-A`. You have to review your relation between A & B, and break the circularity  to resolve your situation.


