== Koin Components

Koin is a DSL to help describe your modules & definitions, a container to make definition resolution. What we need now is
an API to retrieve our instances outside of the container. That's the goal of Koin components.

=== Create a Koin Component

To give a class the capacity to use Koin features, we need to *tag it* with `KoinComponent` interface. Let's take an example.

.A module to define MyService instance
[source,kotlin]
----
class MyService

val myModule = module {
    // Define a singleton for MyService
    single { MyService() }
}
----

we start Koin before using definition.

.Start Koin with myModule
[source,kotlin]
----
fun main(vararg args : String){
    // Start Koin
    startKoin(listOf(myModule))

    // Create MyComponent instance and inject from Koin container
    MyComponent()
}
----

Here is how we can write our `MyComponent` to retrieve instances from Koin container.

.Use get() & by inject() to inject MyService instance
[source,kotlin]
----
class MyComponent : KoinComponent {

    // lazy inject Koin instance
    val myService : MyService by inject()

    // or
    // eager inject Koin instance
    val myService : MyService get()
}
----

=== Unlock the Koin API with KoinComponents

Once you have tagged your class as `KoinComponent`, you gain access to:

* `by inject()` - lazy evaluated instance from Koin container
* `get()` - eager fetch instance from Koin container
* `release()` - release module's instances from its path
* `getProperty()`/`setProperty()` - get/set property


=== Retrieving definitions with get & inject

Koin offers two ways of retrieving instances from the Koin container:

* `val t : T by inject()` - lazy evaluated delegated instance
* `val t : T = get()` - eager access for instance

[source,kotlin]
----
// is lazy evaluated
val myService : MyService by inject()

// retrieve directly the instance
val myService : MyService get()
----

[NOTE]
====
The lazy inject form is better to define property that need lazy evaluation.
====

=== Resolving instance from a name or a module

If you need to filter about visibility (search a definition by name or module), you can specify the following parameter with `get()` or `by inject()`

* `name` - name of the definition (when specified name parameter in your definition)
* `module` - path of the module

Example of module using classes names as modules:

[source,kotlin]
----
val module = module {
    module(ComponentB::class.moduleName) {
        single { ComponentA() }
        single { ComponentB(get()) }
    }

    module(ComponentC::class.moduleName) {
        single { ComponentA() }
        single { ComponentC(get()) }
    }
}

class ComponentA
class ComponentB(val componentA: ComponentA)
class ComponentC(val componentA: ComponentA)
----

We can make the following resolutions:

[source,kotlin]
----
// retrieve from given module
val a_b = get<ComponentA>(module = ComponentB::class.moduleName)
val a_c = get<ComponentA>(module = ComponentC::class.moduleName)
----


=== No inject() or get() in your API?

If your are using an API and want to use Koin inside it, just tag the desired class with `KoinComponent` interface.

