== Using Scopes

Koin brings a simple API to let you define instances that are tied to a limit lifetime.

=== What is a scope?

Scope is a fixed duration of time or method calls in which an object exists.
Another way to look at this is to think of scope as the amount of time an object’s state persists.
When the scope context ends, any objects bound under that scope cannot be injected again (they are dropped from the container).

=== Scope definition

By default in Koin, we have 3 kind of scopes:

- `single` definition, create an object that persistent with the entire container lifetime (can't be dropped).
- `factory` definition, create a new object each time. Short live. No persistence in the container (can't be shared).
- `scope` definition, create an object that persistent tied to the associated scope lifetime.

To declare a scope definition, use the `scope` function with a given scope Id:

[source,kotlin]
----
module {
    scope("scope_id") { Presenter() }
}
----

[IMPORTANT]
====
A scope definition can't be resolved if associated scope has not been created. Then `get<Presenter>()` return an error.
====

=== Create & retrieve a scope

From a `KoinComponent` class, just use the `getKoin()` function to have access to following functions

- `createScope(id : String)` - create a scope with given id in the Koin scope registry
- `getScope(id : String)` - retrieve a previously created scope with given id, from the Koin scope registry
- `getOrCreateScope(id : String)` - create or retrieve if already created, the scope with given id in the Koin scope registry

=== Using a scope

Once you have create a `Scope` instance, let use it to resolve a component:

.from a KoinComponent class
[source,kotlin]
----
module {
    scope("scope_id") { Presenter() }
}

// create a scope
val session = getKoin().createScope("scope_id")

// or get scope if already created before
val session = getKoin().getScope("scope_id")

// will return the same instance of Presenter until Scope 'scope_id' is closed
val presenter = get<Presenter>()
----

Just resolving it: `by inject()` or `get()`. The DSL will indicate which scope to use.

=== Inject it with DSL

If one of your definition need to inject a scope instance, just resolve it ... but be sure to have created the scope before:

[source,kotlin]
----
class Presenter(val userSession : UserSession)
----

Just inject it into constructor, with the right scope:

[source,kotlin]
----
module {
    // Shared user session data
    scope("session") { UserSession() }
    // Inject UserSession instance from "session" Scope
    factory { Presenter(get())}
}
----

=== Closing a scope

Once your scope is finished, just closed it with the `Scope.close()` function:

[source,kotlin]
----
// from a KoinComponent
val session = getKoin().createScope("session")
// will return the same instance of Presenter until 'session' is closed
val presenter = get<Presenter>()

// close it
session.close()
// instance of presenter has been dropped
----

[IMPORTANT]
====
Beware that you can't inject instances anymore from a closed scope.
====

=== Scope callback //TODO

It's also possible to listen scope closing. Just use the `registerScopeCallback()` function to register a `ScopeCallback` instance.

This will notify your `ScopeCallback` on the `onClose(id: String)` function, when a scope has been closed.

[source,kotlin]
----
registerScopeCallback(object : ScopeCallback{
        override fun onClose(id: String) {
            // scope id has been closed
        }
    })
----

=== //TODO Detaching a scope

