== Start Koin

Koin is a DSL, a lightweight container and a pragmatic API. Once you have delcared your definitions wthin Koin modules, your are ready to start the Koi container.

=== The startKoin function

The `startKoin()` function is the main entry point to launch Koin container. It need a *list of Koin modules* to run.
Those modules are read and definitions are ready to be resolved by the Koin container.

.Starting Koin
[source,kotlin]
----
startKoin(listOf(module1,module2 ...))
----

Once `startKoin` has been called, Koin will read all your modules, definitions and will register them to be ready for any `get()` or `by inject()` call.

At start you can also specify several options:

* logging - see <<logging.adoc#_logging,logging>> section
* properties loading (environment, koin.properties file, extra properties ...) - see <<properties.adoc#_lproperties,properties>> section

[IMPORTANT]
====
The `startKoin()` can't be called more than once.
====


=== Behind the start

When we start Koin, we create a `KoinContext` instance in the `StandAloneContext` holder instance which allows us to be agnostic.

This `KoinContext` instance gather all components that forms the Koin container. This class is built by the `Koin` class, the Koin instance builder.
The `Koin` class is responsible to read modules, properties and build a `KoinContext` instance. This instance is then stored in our `StandAloneContext` holder.


=== Loading modules without startKoin function

You can't call the `startKoin()` function more than once. But you can use directly the `loadKoinModules()` functions.

This function is interesting for SDK makers who want to use Koin, because they don't need to use the `starKoin()` function and just use the `loadKoinModules` at the start of their library.

.Load Koin modules
[source,kotlin]
----
loadKoinModules(module1,module2 ...)
----